/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as DeliveriesRunIdRouteImport } from './routes/deliveries.$runId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as ShellStockRouteImport } from './routes/_shell/stock'
import { Route as ShellReconciliationsRouteImport } from './routes/_shell/reconciliations'
import { Route as ShellLivraisonsRouteImport } from './routes/_shell/livraisons'
import { Route as ShellEquipeRouteImport } from './routes/_shell/equipe'
import { Route as ShellEncaissementsRouteImport } from './routes/_shell/encaissements'
import { Route as ShellReglagesRouteRouteImport } from './routes/_shell/reglages/route'
import { Route as ShellReglagesIndexRouteImport } from './routes/_shell/reglages/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ShellReglagesProduitsRouteImport } from './routes/_shell/reglages/produits'
import { Route as ShellReglagesNotificationsRouteImport } from './routes/_shell/reglages/notifications'
import { Route as ShellReglagesLieuxRouteImport } from './routes/_shell/reglages/lieux'
import { Route as ShellReglagesCategoriesRouteImport } from './routes/_shell/reglages/categories'
import { Route as ShellReglagesBoulangerieRouteImport } from './routes/_shell/reglages/boulangerie'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveriesRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const DeliveriesRunIdRoute = DeliveriesRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => DeliveriesRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const ShellStockRoute = ShellStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReconciliationsRoute = ShellReconciliationsRouteImport.update({
  id: '/reconciliations',
  path: '/reconciliations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLivraisonsRoute = ShellLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEquipeRoute = ShellEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEncaissementsRoute = ShellEncaissementsRouteImport.update({
  id: '/encaissements',
  path: '/encaissements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReglagesRouteRoute = ShellReglagesRouteRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReglagesIndexRoute = ShellReglagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellReglagesRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellReglagesProduitsRoute = ShellReglagesProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => ShellReglagesRouteRoute,
} as any)
const ShellReglagesNotificationsRoute =
  ShellReglagesNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ShellReglagesRouteRoute,
  } as any)
const ShellReglagesLieuxRoute = ShellReglagesLieuxRouteImport.update({
  id: '/lieux',
  path: '/lieux',
  getParentRoute: () => ShellReglagesRouteRoute,
} as any)
const ShellReglagesCategoriesRoute = ShellReglagesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShellReglagesRouteRoute,
} as any)
const ShellReglagesBoulangerieRoute =
  ShellReglagesBoulangerieRouteImport.update({
    id: '/boulangerie',
    path: '/boulangerie',
    getParentRoute: () => ShellReglagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/reglages': typeof ShellReglagesRouteRouteWithChildren
  '/encaissements': typeof ShellEncaissementsRoute
  '/equipe': typeof ShellEquipeRoute
  '/livraisons': typeof ShellLivraisonsRoute
  '/reconciliations': typeof ShellReconciliationsRoute
  '/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/reglages/boulangerie': typeof ShellReglagesBoulangerieRoute
  '/reglages/categories': typeof ShellReglagesCategoriesRoute
  '/reglages/lieux': typeof ShellReglagesLieuxRoute
  '/reglages/notifications': typeof ShellReglagesNotificationsRoute
  '/reglages/produits': typeof ShellReglagesProduitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/reglages/': typeof ShellReglagesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/encaissements': typeof ShellEncaissementsRoute
  '/equipe': typeof ShellEquipeRoute
  '/livraisons': typeof ShellLivraisonsRoute
  '/reconciliations': typeof ShellReconciliationsRoute
  '/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/': typeof ShellIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/reglages/boulangerie': typeof ShellReglagesBoulangerieRoute
  '/reglages/categories': typeof ShellReglagesCategoriesRoute
  '/reglages/lieux': typeof ShellReglagesLieuxRoute
  '/reglages/notifications': typeof ShellReglagesNotificationsRoute
  '/reglages/produits': typeof ShellReglagesProduitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/reglages': typeof ShellReglagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/reglages': typeof ShellReglagesRouteRouteWithChildren
  '/_shell/encaissements': typeof ShellEncaissementsRoute
  '/_shell/equipe': typeof ShellEquipeRoute
  '/_shell/livraisons': typeof ShellLivraisonsRoute
  '/_shell/reconciliations': typeof ShellReconciliationsRoute
  '/_shell/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/_shell/': typeof ShellIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/_shell/reglages/boulangerie': typeof ShellReglagesBoulangerieRoute
  '/_shell/reglages/categories': typeof ShellReglagesCategoriesRoute
  '/_shell/reglages/lieux': typeof ShellReglagesLieuxRoute
  '/_shell/reglages/notifications': typeof ShellReglagesNotificationsRoute
  '/_shell/reglages/produits': typeof ShellReglagesProduitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_shell/reglages/': typeof ShellReglagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/deliveries'
    | '/login'
    | '/reglages'
    | '/encaissements'
    | '/equipe'
    | '/livraisons'
    | '/reconciliations'
    | '/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/collections/'
    | '/deliveries/'
    | '/reglages/boulangerie'
    | '/reglages/categories'
    | '/reglages/lieux'
    | '/reglages/notifications'
    | '/reglages/produits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/reglages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/encaissements'
    | '/equipe'
    | '/livraisons'
    | '/reconciliations'
    | '/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/'
    | '/collections'
    | '/deliveries'
    | '/reglages/boulangerie'
    | '/reglages/categories'
    | '/reglages/lieux'
    | '/reglages/notifications'
    | '/reglages/produits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/reglages'
  id:
    | '__root__'
    | '/_shell'
    | '/collections'
    | '/deliveries'
    | '/login'
    | '/_shell/reglages'
    | '/_shell/encaissements'
    | '/_shell/equipe'
    | '/_shell/livraisons'
    | '/_shell/reconciliations'
    | '/_shell/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/_shell/'
    | '/collections/'
    | '/deliveries/'
    | '/_shell/reglages/boulangerie'
    | '/_shell/reglages/categories'
    | '/_shell/reglages/lieux'
    | '/_shell/reglages/notifications'
    | '/_shell/reglages/produits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_shell/reglages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/deliveries/$runId': {
      id: '/deliveries/$runId'
      path: '/$runId'
      fullPath: '/deliveries/$runId'
      preLoaderRoute: typeof DeliveriesRunIdRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/_shell/stock': {
      id: '/_shell/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof ShellStockRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reconciliations': {
      id: '/_shell/reconciliations'
      path: '/reconciliations'
      fullPath: '/reconciliations'
      preLoaderRoute: typeof ShellReconciliationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/livraisons': {
      id: '/_shell/livraisons'
      path: '/livraisons'
      fullPath: '/livraisons'
      preLoaderRoute: typeof ShellLivraisonsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/equipe': {
      id: '/_shell/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof ShellEquipeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/encaissements': {
      id: '/_shell/encaissements'
      path: '/encaissements'
      fullPath: '/encaissements'
      preLoaderRoute: typeof ShellEncaissementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reglages': {
      id: '/_shell/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ShellReglagesRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reglages/': {
      id: '/_shell/reglages/'
      path: '/'
      fullPath: '/reglages/'
      preLoaderRoute: typeof ShellReglagesIndexRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/reglages/produits': {
      id: '/_shell/reglages/produits'
      path: '/produits'
      fullPath: '/reglages/produits'
      preLoaderRoute: typeof ShellReglagesProduitsRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
    '/_shell/reglages/notifications': {
      id: '/_shell/reglages/notifications'
      path: '/notifications'
      fullPath: '/reglages/notifications'
      preLoaderRoute: typeof ShellReglagesNotificationsRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
    '/_shell/reglages/lieux': {
      id: '/_shell/reglages/lieux'
      path: '/lieux'
      fullPath: '/reglages/lieux'
      preLoaderRoute: typeof ShellReglagesLieuxRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
    '/_shell/reglages/categories': {
      id: '/_shell/reglages/categories'
      path: '/categories'
      fullPath: '/reglages/categories'
      preLoaderRoute: typeof ShellReglagesCategoriesRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
    '/_shell/reglages/boulangerie': {
      id: '/_shell/reglages/boulangerie'
      path: '/boulangerie'
      fullPath: '/reglages/boulangerie'
      preLoaderRoute: typeof ShellReglagesBoulangerieRouteImport
      parentRoute: typeof ShellReglagesRouteRoute
    }
  }
}

interface ShellReglagesRouteRouteChildren {
  ShellReglagesBoulangerieRoute: typeof ShellReglagesBoulangerieRoute
  ShellReglagesCategoriesRoute: typeof ShellReglagesCategoriesRoute
  ShellReglagesLieuxRoute: typeof ShellReglagesLieuxRoute
  ShellReglagesNotificationsRoute: typeof ShellReglagesNotificationsRoute
  ShellReglagesProduitsRoute: typeof ShellReglagesProduitsRoute
  ShellReglagesIndexRoute: typeof ShellReglagesIndexRoute
}

const ShellReglagesRouteRouteChildren: ShellReglagesRouteRouteChildren = {
  ShellReglagesBoulangerieRoute: ShellReglagesBoulangerieRoute,
  ShellReglagesCategoriesRoute: ShellReglagesCategoriesRoute,
  ShellReglagesLieuxRoute: ShellReglagesLieuxRoute,
  ShellReglagesNotificationsRoute: ShellReglagesNotificationsRoute,
  ShellReglagesProduitsRoute: ShellReglagesProduitsRoute,
  ShellReglagesIndexRoute: ShellReglagesIndexRoute,
}

const ShellReglagesRouteRouteWithChildren =
  ShellReglagesRouteRoute._addFileChildren(ShellReglagesRouteRouteChildren)

interface ShellRouteChildren {
  ShellReglagesRouteRoute: typeof ShellReglagesRouteRouteWithChildren
  ShellEncaissementsRoute: typeof ShellEncaissementsRoute
  ShellEquipeRoute: typeof ShellEquipeRoute
  ShellLivraisonsRoute: typeof ShellLivraisonsRoute
  ShellReconciliationsRoute: typeof ShellReconciliationsRoute
  ShellStockRoute: typeof ShellStockRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellReglagesRouteRoute: ShellReglagesRouteRouteWithChildren,
  ShellEncaissementsRoute: ShellEncaissementsRoute,
  ShellEquipeRoute: ShellEquipeRoute,
  ShellLivraisonsRoute: ShellLivraisonsRoute,
  ShellReconciliationsRoute: ShellReconciliationsRoute,
  ShellStockRoute: ShellStockRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface DeliveriesRouteChildren {
  DeliveriesRunIdRoute: typeof DeliveriesRunIdRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
}

const DeliveriesRouteChildren: DeliveriesRouteChildren = {
  DeliveriesRunIdRoute: DeliveriesRunIdRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
}

const DeliveriesRouteWithChildren = DeliveriesRoute._addFileChildren(
  DeliveriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  DeliveriesRoute: DeliveriesRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
