/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as DeliveriesRunIdRouteImport } from './routes/deliveries.$runId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as ShellStockRouteImport } from './routes/_shell/stock'
import { Route as ShellReglagesRouteImport } from './routes/_shell/reglages'
import { Route as ShellLivraisonsRouteImport } from './routes/_shell/livraisons'
import { Route as ShellEquipeRouteImport } from './routes/_shell/equipe'
import { Route as ShellEncaissementsRouteImport } from './routes/_shell/encaissements'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveriesRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const DeliveriesRunIdRoute = DeliveriesRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => DeliveriesRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const ShellStockRoute = ShellStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReglagesRoute = ShellReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLivraisonsRoute = ShellLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEquipeRoute = ShellEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEncaissementsRoute = ShellEncaissementsRouteImport.update({
  id: '/encaissements',
  path: '/encaissements',
  getParentRoute: () => ShellRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/encaissements': typeof ShellEncaissementsRoute
  '/equipe': typeof ShellEquipeRoute
  '/livraisons': typeof ShellLivraisonsRoute
  '/reglages': typeof ShellReglagesRoute
  '/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/encaissements': typeof ShellEncaissementsRoute
  '/equipe': typeof ShellEquipeRoute
  '/livraisons': typeof ShellLivraisonsRoute
  '/reglages': typeof ShellReglagesRoute
  '/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/': typeof ShellIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/encaissements': typeof ShellEncaissementsRoute
  '/_shell/equipe': typeof ShellEquipeRoute
  '/_shell/livraisons': typeof ShellLivraisonsRoute
  '/_shell/reglages': typeof ShellReglagesRoute
  '/_shell/stock': typeof ShellStockRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/deliveries/$runId': typeof DeliveriesRunIdRoute
  '/_shell/': typeof ShellIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/deliveries'
    | '/login'
    | '/encaissements'
    | '/equipe'
    | '/livraisons'
    | '/reglages'
    | '/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/collections/'
    | '/deliveries/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/encaissements'
    | '/equipe'
    | '/livraisons'
    | '/reglages'
    | '/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/'
    | '/collections'
    | '/deliveries'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/_shell'
    | '/collections'
    | '/deliveries'
    | '/login'
    | '/_shell/encaissements'
    | '/_shell/equipe'
    | '/_shell/livraisons'
    | '/_shell/reglages'
    | '/_shell/stock'
    | '/collections/$collectionId'
    | '/deliveries/$runId'
    | '/_shell/'
    | '/collections/'
    | '/deliveries/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/deliveries/$runId': {
      id: '/deliveries/$runId'
      path: '/$runId'
      fullPath: '/deliveries/$runId'
      preLoaderRoute: typeof DeliveriesRunIdRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/_shell/stock': {
      id: '/_shell/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof ShellStockRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reglages': {
      id: '/_shell/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ShellReglagesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/livraisons': {
      id: '/_shell/livraisons'
      path: '/livraisons'
      fullPath: '/livraisons'
      preLoaderRoute: typeof ShellLivraisonsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/equipe': {
      id: '/_shell/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof ShellEquipeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/encaissements': {
      id: '/_shell/encaissements'
      path: '/encaissements'
      fullPath: '/encaissements'
      preLoaderRoute: typeof ShellEncaissementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellEncaissementsRoute: typeof ShellEncaissementsRoute
  ShellEquipeRoute: typeof ShellEquipeRoute
  ShellLivraisonsRoute: typeof ShellLivraisonsRoute
  ShellReglagesRoute: typeof ShellReglagesRoute
  ShellStockRoute: typeof ShellStockRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellEncaissementsRoute: ShellEncaissementsRoute,
  ShellEquipeRoute: ShellEquipeRoute,
  ShellLivraisonsRoute: ShellLivraisonsRoute,
  ShellReglagesRoute: ShellReglagesRoute,
  ShellStockRoute: ShellStockRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface DeliveriesRouteChildren {
  DeliveriesRunIdRoute: typeof DeliveriesRunIdRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
}

const DeliveriesRouteChildren: DeliveriesRouteChildren = {
  DeliveriesRunIdRoute: DeliveriesRunIdRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
}

const DeliveriesRouteWithChildren = DeliveriesRoute._addFileChildren(
  DeliveriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  DeliveriesRoute: DeliveriesRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
